create table if not exists public.raw_traces (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  -- source & identity
  source text not null,
  session_id text,
  user_id uuid,

  -- event metadata
  event_type text,
  event_id text,
  timestamp bigint,

  -- DOM / UI context
  url text,
  tag text,
  element_type text,
  name text,
  placeholder text,
  text_content text,
  x_path text,
  container_id bigint,

  -- geometry / position
  client_x double precision,
  client_y double precision,
  width double precision,
  height double precision,

  -- value / state
  value_name text,
  origin_value text,
  value_type text,
  value_index integer,
  value_label text,
  direction text,

  -- keyboard
  code text,
  key text,

  -- message & state
  label text,
  message text,
  event_value text,
  event_state text,
  start_position integer,
  end_position integer,

  -- attribution
  author text,

  constraint raw_traces_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete set null
);
