create table if not exists public.traces (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  event_type text,
  user_id uuid,
  url text,
  page_type text,
  author text,
  message text,
  cursor_position integer,
  end_position integer,
  event_value text,
  tag_name text,
  element_text text,

  offset_x double precision,
  offset_y double precision,
  width double precision,
  height double precision,

  x_path text,
  container_id text,
  event_state text,
  event_id text,
  event_time timestamptz,

  constraint traces_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete set null
);
